In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler,LabelEncoder

In [2]:
dataset=pd.read_csv('/content/health_data.csv')
print("Orginal Datset: ")
print(dataset)

Orginal Datset: 
     Name   Age  BloodPressure Country Diabetes
0    John  28.0          120.0     USA      Yes
1   Sarah   NaN          140.0      UK       No
2     Ali  35.0            NaN     UAE      Yes
3   Maria  50.0          130.0     USA       No
4   Ahmed  40.0          150.0     UAE      Yes
5   Emily  29.0          110.0     NaN       No
6    Omar   NaN          125.0     USA      Yes
7  Sophia  60.0            NaN     USA       No


In [3]:
x=dataset.iloc[:,1:-1].values
y=dataset.iloc[:,-1].values

In [4]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
x[:,0:2]=imputer.fit_transform (x[:,0:2])


In [5]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[2])],remainder='passthrough')
x=ct.fit_transform(x)

In [6]:
le=LabelEncoder()
y=le.fit_transform(y)

In [7]:
scaler=StandardScaler()
x=scaler.fit_transform(x)

In [8]:
print(x)
print("\n preprocessing complete , your data is now clean, numeric and ready to use")

[[-0.57735027 -0.37796447  1.         -0.37796447 -1.2416387  -0.81148222]
 [-0.57735027  2.64575131 -1.         -0.37796447  0.          0.95902445]
 [ 1.73205081 -0.37796447 -1.         -0.37796447 -0.53692484  0.        ]
 [-0.57735027 -0.37796447  1.         -0.37796447  0.97317628  0.07377111]
 [ 1.73205081 -0.37796447 -1.         -0.37796447 -0.0335578   1.84427778]
 [-0.57735027 -0.37796447 -1.          2.64575131 -1.14096529 -1.69673556]
 [-0.57735027 -0.37796447  1.         -0.37796447  0.         -0.36885556]
 [-0.57735027 -0.37796447  1.         -0.37796447  1.97991036  0.        ]]

 preprocessing complete , your data is now clean, numeric and ready to use
